data_root: "data/zju_mocap/CoreView_377"
human: CoreView_377
ann_file: "data/zju_mocap/CoreView_377/annots.npy"
frame_range: [0, 10, 1]
num_train_frame: 10
test_frame_range: [0, 10, 1]
test_novel_range: [10, 15, 1]
max_frame: 15