data_root: "data/people_snapshot_public/male-4-casual"
human: male-4-casual
ann_file: "data/people_snapshot_public/male-4-casual/annots.npy" #//cam
frame_range: [0, 659, 6]
num_train_frame: 659
test_frame_range: [660, 872, 6]
max_frame: 872