data_root: "data/zju_mocap/CoreView_394"
human: CoreView_394
ann_file: "data/zju_mocap/CoreView_394/annots.npy"
frame_range: [0, 661, 1]
num_train_frame: 661
# test_frame_range: [0, 661, 30]
test_frame_range: [0, 661, 1]
test_novel_range: [687, 837, 30]
max_frame: 837