name: gaussian_splatting
channels:
  - pytorch3d
  - pytorch
  - bottler
  - nvidia
  - conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/
  - defaults
dependencies:
  - pytorch==2.0.1 
  - torchvision==0.15.2 
  - torchaudio==2.0.2 
  - pytorch-cuda=11.8
  - tqdm
  - pip=22.3.1
  - plyfile=0.8.1
  - python=3.9.15
  - line_profiler
  - trimesh=3.23.5
  - pytorch3d=0.7.5
  - tensorboardx=2.2
  - pip:
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - open3d==0.17.0
      - scikit-image
      - trimesh==4.0.2
      - pillow==9.5.0
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn

      



