epoch: 10000
save_epoch: 1
num_workers: 8
collator: ''
batch_sampler: 'default'

sampler_meta: 
  min_hw: [256, 256]
  max_hw: [480, 640] 
  strategy: 'range'
shuffle: True
mod: 'train'

# use adam as default
optim : 'adam'
lr : 1e-4
weight_decay : 0.

scheduler: 
  type: 'multi_step' 
  milestones: [80, 120, 200, 240] 
  gamma: 0.5

batch_size: 1

acti_func: 'relu'

use_vgg: False
vgg_pretrained: ''
vgg_layer_name: [0, 0, 0, 0, 0]

use_ssim: False
use_d: False