defaults:
  - _self_
  - gaussian: gaussian
  - train: default
  - test: default
  - subject: zju377

#exp_hyper
data_name: zju_mocap
gpus: 0
local_rank: 0
mod: 'train' #train, test, eval
exp_name: 'gaussian'
reg_resd: True
reg_sigma: False
rgb_only: False
rgb_feature: True
densify_smpl: False
densify_num: 30000
static_test: False
rotate_gaussian: True
reg_res_rot: True
reg_res_scale: True
res_quat: True
resd: True
scalable: True 
debug_gaussian: False
local_rigid: True
num_knn: 5
rigid_loss: False
rot_loss: False
latent_t: True
txyz: True
color_net_width: 64
rot_dependent: False
can_res: True
can_view: True
optimize_non_rigid_from: 0
view_dependent: True
rgb_basis: False
check_ckpt: False
pose_correction: True
optimize_gaussian_until: 20000
init_resq: True
white_bg: False
snapshot: False
vis_free_view: False
bound_mask: True
use_big_pose: True
hash_grid: False
pose_color: True
vis_log: False

mask_loss: False
mse_loss: False
ssim_loss: True
lpips_loss: True

#cam
ratio: 1

#SMPL
smpl_path: "models/SMPL_NEUTRAL.pkl"

type: ""
det: ''
mask_bkgd: True
# white_bg: False

#gaussian
sh_degree: 3
convert_SHs_python: False
compute_cov3D_python: False
debug: False
rgb_feature_dim: 32

#embedder
xyz_res: 10
view_res: 4

#network
num_latent_code: -1

#optimization
iterations: 15000
position_lr_init: 0.00016
position_lr_final: 0.0000016
position_lr_delay_mult: 0.01
position_lr_max_steps: 15000
feature_lr: 0.0025
opacity_lr: 0.05
scaling_lr: 0.005
rotation_lr: 0.01 #0.01 origin
percent_dense: 0.01
deform_lr: 0.001
color_lr: 0.001
pose_lr: 0.00005
sigma_lr: 0.0001
densification_interval: 100
opacity_reset_interval: 500
#2000
densify_from_iter: 500
densify_until_iter: 3000
#10000
densify_grad_threshold: 0.0002
rgb_lr: 0.0025
random_init: False
points_num: 30000
delta_rgb: False
bbox_offset: 0.3
mweight_volume_size: 32
mweight_embedding_size: 256
mweight_dst_voxel_size: 0.0625
volume_weight: False
#reg 
lambda_rigid_loss: 1
lambda_reg_sigma: 0.01
lambda_dssim: 0.2
lambda_rgb: 1
lambda_lpips: 0.015
lambda_reg_resd: 0.01
lambda_reg_res_rot: 0.01 #0.1
lambda_reg_res_scale: 0.01 #0.1
lambda_iso: 1
lambda_rot_loss: 1
lambda_mask_loss: 0.1



big_box: False
box_padding: 0.05
rot_ratio: 0.

task: 'deform'

#epoch 
ep_iter: -1
save_ep: 100
save_latest_ep: 5

#record
log_interval: 100
record_interval: 50
save_ckpt_interval: 1000


animate: False
#data
# data_root: "data/zju_mocap/CoreView_377"
# human: CoreView_377
# ann_file: "data/zju_mocap/CoreView_377/annots.npy"
vertices: "new_vertices"
params: "new_params"
train_view: [0]
test_view: [0]

N_rand: 4096
sample_all: False
#train frame range, start, end, interv
frame_range: [0, 500, 1]

#test
test_frame_range: [0, 500, 30]

#dir
trained_model_dir: 'data/trained_model'
record_dir: 'data/record'
result_dir: 'data/result'
 
training_mode: 'default'
aninerf_animation: False
erode_edge: False 

# evaluation
eval: False
test_novel_pose: False
vis_novel_view: False

fix_random: False

vis: 'mesh'
resume: True


#hydra
hydra:
  job:
    chdir: False
